-- ==========================================
-- SUPABASE SCHEMA SETUP & RLS POLICIES
-- ==========================================
-- Please run this script in your Supabase SQL Editor.

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. PRODUCTS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Product Policies:
-- Anyone can read products (even anonymous users, if you want public viewing)
CREATE POLICY "Anyone can select products" ON public.products
FOR SELECT USING (true);

-- Only admins can insert, update, or delete products
-- Note: 'auth.jwt() -> ''user_metadata'' ->> ''role''' reads from the user's JWT
CREATE POLICY "Admins can insert products" ON public.products
FOR INSERT WITH CHECK (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);

CREATE POLICY "Admins can update products" ON public.products
FOR UPDATE USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);

CREATE POLICY "Admins can delete products" ON public.products
FOR DELETE USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);


-- ==========================================
-- 2. ORDERS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL,
    total_price NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, completed, cancelled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Order Policies:
-- Users can read their own orders. Admins can read all orders.
CREATE POLICY "Users can view own orders or admins can view all" ON public.orders
FOR SELECT USING (
    auth.uid() = user_id OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);

-- Users can insert their own orders.
CREATE POLICY "Users can insert own orders" ON public.orders
FOR INSERT WITH CHECK (
    auth.uid() = user_id
);

-- Only admins can update order statuses.
CREATE POLICY "Admins can update orders" ON public.orders
FOR UPDATE USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);


-- ==========================================
-- 3. MESSAGES TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    admin_reply TEXT,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, resolved
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for messages
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Message Policies:
-- Users can see their own messages. Admins can read all messages.
CREATE POLICY "Users can view own messages or admins can view all" ON public.messages
FOR SELECT USING (
    auth.uid() = user_id OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);

-- Users can insert their own messages.
CREATE POLICY "Users can insert own messages" ON public.messages
FOR INSERT WITH CHECK (
    auth.uid() = user_id
);

-- Admins can update messages to leave replies.
CREATE POLICY "Admins can update messages" ON public.messages
FOR UPDATE USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);


-- ==========================================
-- REALTIME SUBSCRIPTIONS
-- ==========================================
-- Enables Realtime on the `orders` table so the client can listen to INSERT events.
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
